apiVersion: v1
clusters:
- cluster:
    certificate-authority: REPLACE_CA_CERT_PATH
    server: https://127.0.0.1:REPLACE_PORT
  name: REPLACE_CLUSTER_NAME
contexts:
- context:
    cluster: REPLACE_CLUSTER_NAME
    user: REPLACE_CLUSTER_NAME
  name: REPLACE_CLUSTER_NAME
current-context: REPLACE_CLUSTER_NAME
kind: Config
preferences: {}
users:
- name: REPLACE_CLUSTER_NAME
  user:
    client-certificate: REPLACE_CLIENT_CERT_PATH
    client-key: REPLACE_CLIENT_KEY_PATH
